name: Docker Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository name
        run: |
          echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Check directory structure
        run: |
          echo "Repository root contents:"
          ls -la

          if [ -d "oxyz-server" ]; then
            echo "oxyz-server directory exists, checking contents:"
            ls -la oxyz-server
          else
            echo "oxyz-server directory does not exist, checking parent directory:"
            ls -la ..
            if [ -d "../oxyz-server" ]; then
              echo "../oxyz-server directory exists, checking contents:"
              ls -la ../oxyz-server
            fi
          fi

      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./oxyz-server
          file: ./docker/backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
